services:
  node-1:
    image: scytale:latest
    container_name: scytale-node1
    hostname: node1
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      scytale-net:
        ipv4_address: 172.28.1.10
    ports:
      - "127.0.0.1:8332:8332"
    volumes:
      - scytale_node1_data:/data
    command:
      - "scytale-node"
      - "--data-dir"
      - "/data"
      - "--socket"
      - "/run/scytale/node.sock"
      - "start"
      - "--http-bind"
      - "0.0.0.0:8332"
      - "--bootnodes"
      - "/ip4/116.212.72.89/tcp/9000/p2p/12D3KooWMNVcoP79QMoLfg8NKeFyCRfLBq6HngTQpmnkbD9oBWMc"
      - "--mine"
      - "--payout-address"
      - "scy19skhskwa4uv0kectc9q7janqgzqnujd7k90t7dm9vxzhz5wqzyjqd5ztm4"

  node-2:
    image: scytale:latest
    container_name: scytale-node2
    hostname: node2
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      scytale-net:
        ipv4_address: 172.28.2.20
    ports:
      - "127.0.0.1:8333:8333"
    volumes:
      - scytale_node2_data:/data
    command:
      - "scytale-node"
      - "--data-dir"
      - "/data"
      - "--socket"
      - "/run/scytale/node.sock"
      - "start"
      - "--http-bind"
      - "0.0.0.0:8333"
      - "--bootnodes"
      - "/ip4/116.212.72.89/tcp/9000/p2p/12D3KooWMNVcoP79QMoLfg8NKeFyCRfLBq6HngTQpmnkbD9oBWMc"
      - "--mine"
      - "--payout-address"
      - "scy1l4fa8gh0jmpxyytgv6daurhz2p6t24q8f4gus2ydatk8f7vmfalqer6rf0"

  node-3:
    image: scytale:latest
    container_name: scytale-node3
    hostname: node3
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      scytale-net:
        ipv4_address: 172.28.3.30
    ports:
      - "127.0.0.1:8334:8334"
    volumes:
      - scytale_node3_data:/data
    command:
      - "scytale-node"
      - "--data-dir"
      - "/data"
      - "--socket"
      - "/run/scytale/node.sock"
      - "start"
      - "--http-bind"
      - "0.0.0.0:8334"
      - "--bootnodes"
      - "/ip4/116.212.72.89/tcp/9000/p2p/12D3KooWMNVcoP79QMoLfg8NKeFyCRfLBq6HngTQpmnkbD9oBWMc"
      - "--mine"
      - "--payout-address"
      - "scy1rqxn89gtjnty84sc9h8gu3mv55fq49mkuj74fyre4gx7zpttaqmqrxajex"

  node-4:
    image: scytale:latest
    container_name: scytale-node4
    hostname: node4
    networks:
      scytale-net:
        ipv4_address: 172.28.4.40
    ports:
      - "127.0.0.1:8335:8335"
    volumes:
      - scytale_node4_data:/data
    command:
      - "scytale-node"
      - "--data-dir"
      - "/data"
      - "--socket"
      - "/run/scytale/node.sock"
      - "start"
      - "--http-bind"
      - "0.0.0.0:8335"
      - "--bootnodes"
      - "/ip4/116.212.72.89/tcp/9000/p2p/12D3KooWMNVcoP79QMoLfg8NKeFyCRfLBq6HngTQpmnkbD9oBWMc"
      - "--mine"
      - "--payout-address"
      - "scy14ym7kxadjra7fpqe3fsmmr24g57gfe6dxp0zv87fhhsjkhuzdlhshjz840"

networks:
  scytale-net:
    name: scytale-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  scytale_node1_data:
  scytale_node2_data:
  scytale_node3_data:
  scytale_node4_data:
