import { invoke } from '@tauri-apps/api/core';
import { BookOpen, CheckCircle2, Copy, Database, RefreshCw, ShieldCheck } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';

interface Utxo { tx_id: string; output_index: number; amount_quanta: number; confirmations: number; }
interface Mutation { timestamp: string; mutation_type: string; tx_hash: string; delta_quanta: number; running_balance_quanta: number; }
interface PassbookData { passbook_id: string | null; account_number: string | null; public_key: string | null; balance_scy: number; balance_quanta: number; sync_status: string; node_url: string; block_height: number | null; utxos: Utxo[]; ledger: Mutation[]; }

const emptyData: PassbookData = { passbook_id: null, account_number: null, public_key: null, balance_scy: 0, balance_quanta: 0, sync_status: 'Waiting for node', node_url: 'http://127.0.0.1:8332', block_height: null, utxos: [], ledger: [] };
function shortHash(value: string) { return value.length > 18 ? `${value.slice(0, 10)}...${value.slice(-8)}` : value || '—'; }
function formatTime(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toISOString().slice(0, 19).replace('T', ' '); }

export function PassbookCanvas({ activeWalletPath }: { activeWalletPath: string | null }) {
    const { t } = useTranslation();
    const [data, setData] = useState<PassbookData>(emptyData);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');
    const refresh = useCallback(async () => {
        setLoading(true); setError('');
        try { setData(await invoke<PassbookData>('get_passbook_ledger', { walletPath: activeWalletPath, nodeUrl: null })); }
        catch (reason) { setError(String(reason)); }
        finally { setLoading(false); }
    }, [activeWalletPath]);
    useEffect(() => { void refresh(); }, [refresh]);
    return (
        <section id="workbench-passbook-canvas" className="min-h-0 flex-1 overflow-y-auto bg-[#071015] p-4 text-zinc-100 md:p-6">
            <div className="mx-auto max-w-6xl space-y-4">
                <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.25em] text-cyan-400">PASSBOOK // CRYPTOGRAPHIC LEDGER</p><h2 className="mt-1 text-xl font-semibold">{t('passbook.title')}</h2><p className="mt-1 text-xs text-zinc-500">{data.public_key ? `Public key ${shortHash(data.public_key)}` : 'No public key loaded'}</p></div><button type="button" onClick={() => void refresh()} disabled={loading} title={t('passbook.refresh')} className="flex items-center gap-2 rounded border border-cyan-500/30 bg-cyan-500/10 px-3 py-2 font-mono text-[10px] text-cyan-300 hover:bg-cyan-500/20 disabled:opacity-50"><RefreshCw className={`h-3.5 w-3.5 ${loading ? 'animate-spin' : ''}`} />{t('passbook.refresh')}</button></header>
                <div className="rounded-xl border border-emerald-400/30 bg-gradient-to-br from-emerald-500/15 via-zinc-900/90 to-cyan-500/10 p-5 shadow-[0_0_40px_rgba(16,185,129,0.08)]"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-3"><div className="rounded-lg border border-emerald-400/40 bg-emerald-400/10 p-2"><ShieldCheck className="h-5 w-5 text-emerald-300" /></div><div><p className="font-mono text-[10px] uppercase tracking-widest text-emerald-300">VERIFIED PASSBOOK</p><p className="mt-1 font-mono text-xs text-zinc-300">{data.passbook_id ?? 'scy1_passbook_pending'}</p></div></div><span className="flex items-center gap-1.5 rounded-full border border-emerald-500/30 px-2 py-1 font-mono text-[10px] text-emerald-300"><CheckCircle2 className="h-3 w-3" /> PIN Vault verified</span></div><div className="mt-6 grid gap-5 md:grid-cols-[1.2fr_1fr_1fr]"><div><p className="text-[10px] uppercase tracking-wider text-zinc-500">Active balance</p><p className="mt-1 font-mono text-3xl font-semibold tracking-tight text-white">{data.balance_scy.toFixed(8)} <span className="text-sm text-emerald-300">SCY</span></p><p className="mt-1 font-mono text-[10px] text-zinc-500">1 SCY = 100,000,000 quanta · {data.balance_quanta.toLocaleString()} quanta</p></div><div><p className="text-[10px] uppercase tracking-wider text-zinc-500">Account Number</p><p className="mt-2 font-mono text-sm text-cyan-200">{data.account_number ?? '—'}</p><p className="mt-4 text-[10px] uppercase tracking-wider text-zinc-500">Derivation Path</p><p className="mt-2 font-mono text-xs text-zinc-300">m/0'/0'</p></div><div><p className="text-[10px] uppercase tracking-wider text-zinc-500">Sync status</p><p className="mt-2 flex items-center gap-1.5 font-mono text-xs text-emerald-300"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />{data.sync_status}</p><p className="mt-4 font-mono text-[10px] text-zinc-500">{data.node_url} · Block #{data.block_height?.toLocaleString() ?? '—'}</p></div></div></div>
                {error && <p className="rounded border border-orange-500/30 bg-orange-500/10 p-3 font-mono text-xs text-orange-300">{error}</p>}
                <div className="grid gap-4 lg:grid-cols-[1fr_1.25fr]"><div className="rounded border border-zinc-800 bg-zinc-900/70 p-4"><div className="mb-3 flex items-center gap-2"><Database className="h-4 w-4 text-cyan-300" /><h3 className="text-xs font-semibold">UTXO Output Breakdown</h3></div><div className="space-y-2">{data.utxos.length === 0 && <p className="py-5 text-center font-mono text-[10px] text-zinc-600">No unspent outputs returned by node.</p>}{data.utxos.map((utxo) => <div key={`${utxo.tx_id}-${utxo.output_index}`} className="rounded border border-zinc-800 bg-zinc-950/70 p-3 font-mono text-[10px]"><div className="flex justify-between text-zinc-400"><span>{shortHash(utxo.tx_id)}</span><span>#{utxo.output_index}</span></div><div className="mt-2 flex justify-between"><span className="text-cyan-300">{utxo.amount_quanta.toLocaleString()} quanta</span><span className="text-emerald-300">{utxo.confirmations} confirmations</span></div></div>)}</div></div><div className="rounded border border-zinc-800 bg-zinc-900/70 p-4"><div className="mb-3 flex items-center gap-2"><BookOpen className="h-4 w-4 text-emerald-300" /><h3 className="text-xs font-semibold">Synchronized Mutation History</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left font-mono text-[10px]"><thead className="border-b border-zinc-800 text-zinc-500"><tr><th className="pb-2">Timestamp</th><th className="pb-2">Type</th><th className="pb-2">Tx Hash</th><th className="pb-2 text-right">Change</th><th className="pb-2 text-right">Running Balance</th></tr></thead><tbody>{data.ledger.length === 0 && <tr><td colSpan={5} className="py-6 text-center text-zinc-600">No ledger mutations returned by node.</td></tr>}{data.ledger.map((mutation, index) => <tr key={`${mutation.tx_hash}-${index}`} className="border-b border-zinc-900"><td className="py-2 text-zinc-500">{formatTime(mutation.timestamp)}</td><td className="py-2 text-zinc-300">{mutation.mutation_type}</td><td className="py-2 text-zinc-500">{shortHash(mutation.tx_hash)}</td><td className={`py-2 text-right ${mutation.delta_quanta >= 0 ? 'text-emerald-300' : 'text-orange-300'}`}>{mutation.delta_quanta >= 0 ? '+' : ''}{mutation.delta_quanta.toLocaleString()}</td><td className="py-2 text-right text-cyan-200">{mutation.running_balance_quanta.toLocaleString()}</td></tr>)}</tbody></table></div></div></div>
                <p className="flex items-center gap-2 font-mono text-[10px] text-zinc-600"><Copy className="h-3 w-3" /> Direct node sync preserves passbook_id, UTXO, mempool, and payload terminology.</p>
            </div>
        </section>
    );
}
