[package]
name = "scytale-primitives"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Fundamental primitives, cryptographic wrappers, and common types for Scytale"

[lints]
workspace = true

[dependencies]
blake3 = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
